apiVersion: v1
kind: Pod
metadata:
  name: security-pod
spec:
  containers:
    - name: security-probe
      image: <security_image>:latest
      args:
        - --some-arg=foo
      resources:
        limits:
          cpu: "1"
          memory: 200Mi
        requests:
          cpu: 250m
          memory: 64Mi
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop:
            - ALL