apiVersion: v1
kind: Pod
metadata:
  name: security-probe
spec:
  containers:
    - name: security-probe
      image: <YOUR_IMAGE> # Replace with your desired container image
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "1"
          memory: "2Gi"
      securityContext:
        privileged: false
        runAsNonRoot: true
        runAsUser: 65534
      readinessProbe:
        exec:
          command:
            - <YOUR_SECURITY_PROBE> # Replace with your desired security probe