apiVersion: v1
kind: Pod
metadata:
  name: security-probe-pod
spec:
  automountServiceAccountToken: false # Disable service account token mounting
  containers:
    - name: security-probe
      image: <image_name>:<tag>
      command: ["security_probe"]
      args: ["--target=<ip/url>", "--user=<username>", "--password=<password>"]
      env:
        - name: TARGET_ENV
          value: "<target_env>"
        - name: PROBE_LEVEL
          value: "<probe_level>"
      volumeMounts: # Mount secrets to provide credentials to connect to the target
        - name: secret-volume
          mountPath: /var/run/secret/credentials
      securityContext:
        runAsNonRoot: true # Run as a non-root user
        readOnlyRootFilesystem: true # Set Read Only File System (ROOTFS) to prevent file tampering
        allowPrivilegeEscalation: false # Prevent privilege escalation attacks
  volumes:
    - name: secret-volume
      secret:
        defaultMode: 0420 # Enforce restricted access mode on secrets volume files (read-only for owner and group, no permissions for others)
        secretName: security-probe-credentials