apiVersion: v1
kind: Pod
metadata:
  name: security-probe
spec:
  containers:
    - name: probe
      image: <image_name>
      envFrom:
        - configMapRef:
            name: <configmap_name>
      volumeMounts:
        - mountPath: /secrets
          name: secrets-volume
  volumes:
    - name: secrets-volume
      secret:
        secretName: <secret_name>