apiVersion: v1
kind: Pod
metadata:
  name: security-probe
spec:
  containers:
    - name: security-probe
      image: security/probes
      ports:
        - containerPort: 8080
          protocol: TCP