apiVersion: v1
kind: Pod
metadata:
  name: security-probe
spec:
  containers:
    - name: security-probe
      image: <image_name>
      command: ["<command>", "<argument>"] # Insert the specific command and arguments for your security probe here